version: "3.7"

services: 
    api:        
        image: eisandbar/anbox
        build: ./API
        depends_on:
            - db
        volumes:
            - ./:/app
        networks:
            - db-net
        ports:
            - "3333:3333"
        restart: on-failure
        environment:
            POSTGRES_USER: pguser
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: pgdb
            POSTGRES_HOST: db

    db:
        image: postgres
        volumes:
            - ./postgres/data:/var/lib/postgresql/data
        networks:
            - db-net
        restart: on-failure
        environment:
            POSTGRES_USER: pguser
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: pgdb

networks:
    db-net:


volumes:
    postgres: